name: Input Test
description: Test
title: "[Test]: Input"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Service"
  - type: input
    attributes:
      label: "Service Name"
    validations:
      required: true
  - type: dropdown
    id: os 
    attributes:
      label: "Choose your OS"
      options:
        - ''
        - MacOS
        - Linux
        - Windows
        - それ以外
      default: 0
  - type: checkboxes
    id: checkbox
    attributes:
      label: 選ぶのだ
      description: "さあ、選びたまえ"
      options:
        - label: "生ぎだいっ!"
        - label: "船降りろ"
