name: Input Test
description: Test
title: "[Test]: Input"
body:
  - type: markdown
    attributes:
      value: "## Service"
  - type: input
    attributes:
      label: "Service Name"
    validations:
      required: true
  - type: dropdown
    id: os 
    attributes:
      label: "Choose your OS"
      options:
        - ''
        - MacOS
        - Linux
        - Windows
      default: 0
