name: Input Test
description: Test
body:
  - type: markdown
    attributes:
      value: "## Service"
  - type: input
    attributes:
      label: "Service Name"
    validations:
      required: true
