name: Convert md to html
on:
  issues:
    types:
      - opened
jobs:
  Convert:
    name: Convert to html
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.label }} == "need-convert"
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Get issue body
        run: echo "${{ github.event.issue.body }}" > body.md

      - name: Install showdown
        run: npm install showdown -g

      - name: Convert
        id: convert
        run: |
          echo `cat style.css` >> body.md
          showdown makehtml -i body.md -o out.html -c tasklists
          echo out=`cat out.html` >> $GITHUB_OUTPUT

      - name: comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Converted HTML

            <details><summary>Converted HTML</summary>

            \`\`\`html
            ${{ steps.convert.outputs.out }}
            \`\`\`

            </details>`
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
