name: Convert md to html
on:
  issues:
    types:
      - opened
jobs:
  Convert:
    name: Convert to html
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.label }} == "need-convert"
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    env:
      BODY: issues/${{ github.event.issue.number }}/body.md
      OUT: issues/${{ github.event.issue.number }}/out.html
      TMP: tmp.txt

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Checkout branch
        run: |
          git checkout -b update/issue-${{ github.event.issue.number }}
          mkdir issues/${{ github.event.issue.number }}

      - name: Get issue body
        run: echo "${{ github.event.issue.body }}" > ${{ env.BODY }}

      - name: Install showdown
        run: npm install showdown -g

      - name: Convert
        id: convert
        # showdownがstdinからの読み込みをサポートしていないのでtmpファイルを利用する
        run: |
          echo "`cat style.css ${{ env.BODY }}`" > ${{ env.TMP }}
          showdown makehtml -i ${{ env.TMP }} -o ${{ env.OUT }} -c tasklists -c ghCodeBlocks -c ghCompatibleHeaderId
          echo out="`cat ${{ env.OUT }}`" >> $GITHUB_OUTPUT
          rm -f ${{ env.TMP }}

      - name: comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Converted HTML

            <details><summary>Converted HTML</summary>

            \`\`\`html
            ${{ steps.convert.outputs.out }}
            \`\`\`

            </details>`
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email action@github.com
          git config --global user.name actionbot

          git add .
          git commit -m "Update issue"
          git push origin update/issue-${{ github.event.issue.number }}
          gh pr create -t "Update Issue" -b "closes: #${{ github.event.issue.number }}"
